spring:
  datasource:
    url: jdbc:mysql://47.105.165.183:3306/helper?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: root1234@#


# 关闭安全验证
management:
  security:
    enabled: false


# mybatis-plus相关配置
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:**/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: 'null'

helper:
  #安全认证
  auth:
    # token过期时间（分钟）
    tokenExpireTime: 60
    # 用户选择保存登录状态对应token过期时间（天）
    saveLoginTime: 7
    # 限制用户登陆错误次数（次）
    loginTimeLimit: 10
    # 错误超过次数后多少分钟后才能继续登录（分钟）
    loginAfterTime: 10
    ignoreUrls:
      - /app/user/register
      - /login
      - /api/system/user/getCurrentUserInfo
      - /index
      - /logout
      - /swagger-ui.html
      #      - /swagger-resources/**
      - /swagger-resources/configuration/ui
      - /swagger-resources
      - /v2/api-docs
      - /swagger-resources/configuration/security
      #      - /swagger/**
      #      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico

robot:
  url: http://api.qingyunke.com/api.php?key=free&appid=0&msg=
